name: Gerar Cobrinha do GitHub

on:
  schedule:
    - cron: "0 0 * * *"  # Executa todos os dias à 00:00 UTC
  workflow_dispatch:
  push:

jobs:
  generate:
    name: Gerar Snake
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Gerar a cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: barbarabastossantos
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake.gif

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
